services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cardb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
  mailhog:
    image: mailhog/mailhog
    container_name: car_rent_mailhog
    ports:
      - "1025:1025" # SMTP (Tətbiqin qoşulması üçün)
      - "8025:8025" # Web UI (Sənin brauzerdən baxmağın üçün)

  app:
    image: car-rent
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cardb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_PROFILES_ACTIVE: dev
      SENDGRID_ENABLED: "false"
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
    depends_on:
      - db
      - mailhog
